[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "wipe", "--transition-fps", "60"]

[templates.kitty]
input_path = "./templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"
post_hook = 'pkill -SIGUSR1 kitty'

[templates.hyprland]
input_path = "./templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"
post_hook = 'hyprctl reload'

[templates.rofi]
input_path = "./templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.quickshell]
input_path = "./templates/quickshell-colors.qml"
output_path = "~/.config/quickshell/modules/config/Colors.qml"

[templates.gtk3]
input_path = "./templates/gtk-colors.css"
output_path = "~/.config/gtk-3.0/colors.css"
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3'

[templates.gtk4]
input_path = "./templates/gtk-colors.css"
output_path = "~/.config/gtk-4.0/colors.css"

[templates.qt5ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.discord]
input_path = './templates/discord.css'
output_path = '~/.var/app/com.discordapp.Discord/config/Vencord/themes/midnight.css'
